server:
  port: 8080

spring:

  application:
    name: api-gateway

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "http://localhost:8085/realms/client-app"

  cloud:
    gateway:
      routes:
        - id: driver-app
          uri: lb://driver-app
          predicates:
            - Path=/driver-app/**
        - id: client-app
          uri: lb://client-app
          predicates:
            - Path=/client-app/**
        - id: server-app
          uri: lb://server-app
          predicates:
            - Path=/server-app/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

logging:
  level:
    org:
      springframework:
        web: DEBUG
